<script lang="ts">
  import Seo from '$lib/components/Seo.svelte';
  import { seoData } from '$lib/config/seo';

  const effectiveDate = new Date().toISOString().split('T')[0];
</script>

<Seo
  title={seoData.routes.privacy.title}
  description={seoData.routes.privacy.description}
  keywords={seoData.routes.privacy.keywords}
/>

<div class="container mx-auto px-6 py-20 max-w-4xl">
  <h1 class="text-3xl md:text-5xl font-bold text-white mb-6">Privacy Policy</h1>
  <p class="text-zinc-400 mb-12">
    Effective date: <span class="text-emerald-400 font-semibold"
      >{effectiveDate}</span
    >
  </p>

  <div class="prose prose-invert prose-lg max-w-none text-zinc-300">
    <p class="lead text-xl text-zinc-200">
      We believe that your chat data belongs to you. Sidecar is designed to be
      privacy-first, operating entirely locally within your browser.
    </p>

    <h2>1. Data Collection & Usage</h2>
    <p>
      Sidecar is a client-side browser extension. We do not transmit your
      personal data, chat history, or API keys to any external servers.
    </p>
    <ul>
      <li>
        <strong>Local Processing:</strong> All macros, settings, and temporary data
        are stored locally on your device using the Chrome Storage API.
      </li>
      <li>
        <strong>No Analytics:</strong> We do not track your usage behavior or collect
        telemetry data.
      </li>
      <li>
        <strong>No Third-Party Sharing:</strong> Since we don't collect your data,
        we cannot (and will not) share it with third parties.
      </li>
    </ul>

    <h2>2. Permissions</h2>
    <p>To function correctly, Sidecar requires specific browser permissions:</p>
    <ul>
      <li>
        <code>storage</code>: Used to save your preferences, macros, and
        interface settings.
      </li>
      <li>
        <code>activeTab</code>: Used only when you activate the extension to
        inject the Sidecar interface into the current ChatGPT tab.
      </li>
      <li>
        <code>host_permissions</code> (chatgpt.com): Required to modify the page
        layout (Wide Mode) and add the Dock interface.
      </li>
    </ul>

    <h2>3. Data Retention</h2>
    <p>
      All data generated by Sidecar (such as saved macros) lives on your device.
      Uninstalling the extension removes this data permanently from your
      browser.
    </p>

    <h2>4. Changes to This Policy</h2>
    <p>
      We may update our Privacy Policy from time to time. We will notify you of
      any changes by posting the new Privacy Policy on this page.
    </p>

    <h2>5. Contact Us</h2>
    <p>
      If you have any questions about this Privacy Policy, please contact us via
      our <a
        href={seoData.product.social.github}
        class="text-emerald-400 hover:underline">GitHub Repository</a
      >.
    </p>
  </div>
</div>
